### ISSUE TITLE
Intro skip and borderless windowed

### ISSUE THREAD

**Issue by Keith94** [Lyall/SotDFix#1]
The only two things I think are missing. Thanks for the fix btw. 👍

**Comment by Lyall** [comment]
Not sure on the intro skip, they seem to be using a bespoke sequence for that. 

As for borderless, the game already has it. Fullscreen in this game is borderless by default.

**Comment by Keith94** [comment]
> Fullscreen in this game is borderless by default.

Oops I did not even realize it. Thanks

-nostartupmovies flag did not work and all game files are packed. Weird.

**Comment by Lyall** [comment]
> > Fullscreen in this game is borderless by default.
> 
> Oops I did not even realize it. Thanks
> 
> -nostartupmovies flag did not work and all game files are packed. Weird.

The intro logos are an in-game sequence, not video.  Would probably need to skip parts of the sequence or even the entire thing outright. Also the "data.vfs" file can be unpacked with [this python script](https://github.com/LinkOFF7/GameReverseScripts/blob/main/sotd_hella_remastered_vfs3_extract.py).

**Comment by Keith94** [comment]
Nice find. I'll check if the game will read the unpacked files too.
